name: Dynamic README injection
on:
  schedule:
    # Cette tâche s'exécute automatiquement toutes les heures
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  get-office-quotes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Let the magic happen
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Mettez à jour avec la version que vous souhaitez utiliser

      - run: yarn

      - run: node .

      - name: Add to git repo
        run: |
          git config pull.rebase false
          git pull
          git add .
          git config --global user.name "adambour"
          git config --global user.email "bouradam.adam@gmail.com"
          git commit -m "[Automated] README updated with new Office quote!" || echo "No changes to commit"  # Ignore si aucune modification

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
